include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - lib/presentation/core/language/locale_keys.g.dart
    - lib/injection.config.dart

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
