include: package:very_good_analysis/analysis_options.yaml
analyzer:
  enable-experiment:
    - nonfunction-type-aliases

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
